name = "iplc-ai"
main = "src/index.ts"
compatibility_date = "2024-03-11"
compatibility_flags = ["nodejs_compat"]
account_id = "265122b6d6f29457b0ca950c55f3ac6e"

[observability]
enabled = true

# AI binding for Workers AI
[ai]
binding = "AI"

# Vectorize index for document embeddings
[[vectorize]]
binding = "DOC_INDEX"
index_name = "doc-index"

# KV namespaces for data storage - using the same IDs as the parent project
[[kv_namespaces]]
binding = "USER_SESSIONS"
id = "92ec4b43378242efaad5c898e961f8981"
preview_id = "92ec4b43378242efaad5c898e961f8981"

[[kv_namespaces]]
binding = "DOCUMENTS"
id = "995f435153f84382a70fff8ab3a8e892"
preview_id = "995f435153f84382a70fff8ab3a8e892"

[[kv_namespaces]]
binding = "RATE_LIMITER"
id = "30dd285e5d5a4cabafbd9fae69ba5d5e"
preview_id = "30dd285e5d5a4cabafbd9fae69ba5d5e"

[[kv_namespaces]]
binding = "SESSION"
id = "a4926bc00e9b438a898289934457a579"
preview_id = "a4926bc00e9b438a898289934457a579"

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = "11baf1c1465d4b03afbe59fdfcdfe1b8"
preview_id = "11baf1c1465d4b03afbe59fdfcdfe1b8"

# Durable Objects configuration
[[durable_objects.bindings]]
name = "AI_GATE"
class_name = "AIGate"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AIGate"]

[[migrations]]
tag = "v3-aigate-sqlite"